apiVersion: 1

datasources:
  - name: PostgreSQL (LiteLLM DB)
    type: postgres
    access: proxy
    url: db:5432
    user: llmproxy
    secureJsonData:
      password: dbpassword9090
    jsonData:
      database: litellm
      sslmode: disable
    isDefault: false
    editable: false
